### ISSUE TITLE
ModuleNotFoundError: No module named 'bitters.modules.image_tokenizer'

### ISSUE THREAD

**Issue by JEONG8652** [tgisaturday/BITTERS#1]
```
Traceback (most recent call last):
  File "train_vae.py", line 4, in <module>
    from bitters.loader import ImageDataModule
  File "/BITTERS/bitters/loader.py", line 20, in <module>
    from bitters.modules.image_tokenizer.tokenizer import DiscreteImageTokenizer
ModuleNotFoundError: No module named 'bitters.modules.image_tokenizer'
```

I tried to train BITTERS model on docker environment and it returns this error,
It seems like there is no directory or file `image_tokenizer` in `bitters/module`, is it missing?
Thank you.

**Comment by tgisaturday** [comment]
Hi, thank you for letting me know. Please clone newly updated version and let me know if the error persists.

**Comment by JEONG8652** [comment]
Now it works fine! Thank you for fixing!
